# Aula 07 - Manipulação de Strings com Python

> Uma variável primária de texto é chamada de char ou caracter possibilitando o armazenamento de 8 bit de memória. Quando necessitamos de um conujunto de caracteres utilizamos um objetom ou variáveis compostas no caso da maioria das linguagens chamadas de string. Vamos ver como se aplica.

In [24]:
frase = "Boa tarde a todos"
print(frase)
saudacao = frase[0:9]
print(saudacao)

Boa tarde a todos
Boa tarde


In [18]:
print(type(frase))
print(type(saudacao))

<class 'str'>
<class 'str'>


In [23]:
print(frase.count(' '))
print(saudacao.count(' '))

3
1


In [25]:
print(len(frase))
print(len(saudacao))

17
9


In [29]:
frase = frase.replace("a todos","galerinha!")
print(frase)
saudacao = saudacao.replace("tarde", "noite")
print(saudacao)

Boa tarde galerinha!
Boa noite


In [32]:
frase = [i for i in frase]
print(frase)

['B', 'o', 'a', ' ', 't', 'a', 'r', 'd', 'e', ' ', 'g', 'a', 'l', 'e', 'r', 'i', 'n', 'h', 'a', '!']


In [35]:
for x in frase:
    print(x)

B
o
a
 
t
a
r
d
e
 
g
a
l
e
r
i
n
h
a
!


## Exercício 1
> Crie um código para a seguinte frase: "Sabia que o sábia sabia assobiar?" reparticionando por espaços ,após isso crie um print format para visualizar cada palavra em uma coluna separada.

In [36]:
frase = "Sabia que o sábia sabia assobiar?"
frase = [x for x in frase]
print(frase)

['S', 'a', 'b', 'i', 'a', ' ', 'q', 'u', 'e', ' ', 'o', ' ', 's', 'á', 'b', 'i', 'a', ' ', 's', 'a', 'b', 'i', 'a', ' ', 'a', 's', 's', 'o', 'b', 'i', 'a', 'r', '?']


## Correção


In [1]:
frase = "Sabia que o sabiá sabia assobiar"

palavras = frase.split()

for i in range(max(len(x) for x in palavras)):
    for y in palavras:
        print(y[i] if i < len(y) else ' ', end = ' ')

    print()

S q o s s a 
a u   a a s 
b e   b b s 
i     i i o 
a     á a b 
          i 
          a 
          r 


In [2]:
for i in range(max (len (x) for x in palavras)):
    print('   '.join(x[i] if i<len(x) else ' ' for x in palavras))

S   q   o   s   s   a
a   u       a   a   s
b   e       b   b   s
i           i   i   o
a           á   a   b
                    i
                    a
                    r


# Introdução a Numpy

> Numpy é uma biblioteca python para desenvolvimento de matrizes. tem por objetivos facilitar na criação de algoritmos matemáticos para solucionar paradgimas avançados em relação a arrays. 

In [3]:
pip install numpy

     ---------------------------------------- 0.0/59.7 kB ? eta -:--:--
     ------ --------------------------------- 10.2/59.7 kB ? eta -:--:--
     ------------- ------------------------ 20.5/59.7 kB 162.5 kB/s eta 0:00:01
     ------------- ------------------------ 20.5/59.7 kB 162.5 kB/s eta 0:00:01
     ------------- ------------------------ 20.5/59.7 kB 162.5 kB/s eta 0:00:01
     -------------------------- ----------- 41.0/59.7 kB 140.3 kB/s eta 0:00:01
     -------------------------------- ----- 51.2/59.7 kB 163.8 kB/s eta 0:00:01
     -------------------------------------- 59.7/59.7 kB 176.2 kB/s eta 0:00:00
   ---------------------------------------- 0.0/12.9 MB ? eta -:--:--
    --------------------------------------- 0.2/12.9 MB 6.1 MB/s eta 0:00:03
   - -------------------------------------- 0.5/12.9 MB 5.3 MB/s eta 0:00:03
   -- ------------------------------------- 0.8/12.9 MB 6.5 MB/s eta 0:00:02
   --- ------------------------------------ 1.1/12.9 MB 6.5 MB/s eta 0:00:


[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: C:\Users\march\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [4]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [5]:
b = np.array([(1,2,3), (4,5,6)])
print(b)

[[1 2 3]
 [4 5 6]]


> Para demostrar '1'

In [6]:
c = np.ones((3,3))
print(c)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


> Para demostrar valores binários

In [7]:
d = np.eye(5)
print(d)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


> Para demostrar o maior valor

In [8]:
print(a.max())
print(b.max())
print(c.max())

3
6
1.0


> Para demostrar o menor valor

In [9]:
print(a.min())
print(b.min())
print(c.min())

1
1
1.0


> Para calcular soma

In [10]:
print(a.sum())
print(b.sum())
print(c.sum())

6
21
9.0


> Para calcular média

In [11]:
print(a.mean())
print(b.mean())
print(c.mean())

2.0
3.5
1.0


> Para desvio padrão

In [12]:
print(round(a.std(),2))
print(round(b.std(),2))
print(round(c.std(),2))

0.82
1.71
0.0


## Exercício 2

> Crie uma matriz chamada contar com os números de 0 até 9. Ao final crie uma contagem, média e desvio de padrão dessa matriz. Para adicionar de 0 a 9 utilize o for e depois atribua à matriz.

In [15]:
contar = np.array([i for i in range(10)])
print("Contagem:", contar)
print("Média:", contar.mean())
print("Desvio de Padrão:", round(contar.std(),2))

Contagem: [0 1 2 3 4 5 6 7 8 9]
Média: 4.5
Desvio de Padrão: 2.87
